Advanced-Database-and-ORM-Concepts_Assignment 1/Models/Podcast.cs
using System.ComponentModel.DataAnnotations;

namespace Advanced_Database_and_ORM_Concepts_Assignment_1.Models
{
    public class Podcast
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(20, ErrorMessage = "Must be betweeen 3 and 20 characters", MinimumLength = 3)]
        [Display(Name = "Podcast Title")]
        public string PodcastTitle { get; set; }
        public virtual HashSet<Artist> Artists { get; set; } = new HashSet<Artist>();
        public virtual List<Episode> Episodes { get; set; } = new List<Episode>();
        public virtual HashSet<ListenerList> ListenerLists { get; set; } = new HashSet<ListenerList>();
        public Podcast() { }
        public Podcast(string podcastTitle)
        {
            PodcastTitle = podcastTitle;
        }
    }
}

Advanced-Database-and-ORM-Concepts_Assignment 1/Controllers/PodcastsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Advanced_Database_and_ORM_Concepts_Assignment_1.Data;
using Advanced_Database_and_ORM_Concepts_Assignment_1.Models;
using Advanced_Database_and_ORM_Concepts_Assignment_1.Models.ViewModels;

namespace Advanced_Database_and_ORM_Concepts_Assignment_1.Controllers
{
    public class PodcastsController : Controller
    {
        private readonly Advanced_Database_and_ORM_Concepts_Assignment_1Context _context;

        public PodcastsController(Advanced_Database_and_ORM_Concepts_Assignment_1Context context)
        {
            _context = context;
        }

        // GET: Podcasts
        public async Task<IActionResult> Index()
        {
            List<Podcast> podcasts = await _context.Podcast
              .Include(a => a.Artists)
              .Include(b => b.Episodes)
              .Include(c => c.ListenerLists)
              .ToListAsync();

            return View(podcasts);
        }

        public List<Episode> GetEpisode(int podcastId)
        {
            Podcast podcast = _context.Podcast
                .Include(a => a.Episodes)
                .FirstOrDefault(b => b.Id == podcastId);

            return podcast.Episodes;
        }
        // GET: Podcasts/Details/5
        public IActionResult Details(int? id, string sortFunction = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            Podcast podcast = _context.Podcast
                .FirstOrDefault(a => a.Id == id);


            if (podcast == null)
            {
                return NotFound();
            }

            List<Episode> episodes = GetEpisode(podcast.Id);

            if (sortFunction == "chronological")
            {
                episodes = episodes.OrderBy(e => e.AirDate).ToList();
            }
            else if (sortFunction == "reverse-chronological")
            {
                episodes = episodes.OrderByDescending(e => e.AirDate).ToList();
            }

            EpisodeListVM vm = new EpisodeListVM
            {
                Episodes = episodes,
                SortFunction = sortFunction
            };

            return View(vm);
        }

        // GET: Podcasts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Podcasts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PodcastTitle")] Podcast podcast)
        {
            if (ModelState.IsValid)
            {
                _context.Add(podcast);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(podcast);
        }

        // GET: Podcasts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Podcast == null)
            {
                return NotFound();
            }

            var podcast = await _context.Podcast.FindAsync(id);
            if (podcast == null)
            {
                return NotFound();
            }
            return View(podcast);
        }

        // POST: Podcasts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PodcastTitle")] Podcast podcast)
        {
            if (id != podcast.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(podcast);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PodcastExists(podcast.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(podcast);
        }

        // GET: Podcasts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Podcast == null)
            {
                return NotFound();
            }

            var podcast = await _context.Podcast
                .FirstOrDefaultAsync(m => m.Id == id);
            if (podcast == null)
            {
                return NotFound();
            }

            return View(podcast);
        }

        // POST: Podcasts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Podcast == null)
            {
                return Problem("Entity set 'Advanced_Database_and_ORM_Concepts_Assignment_1Context.Podcast'  is null.");
            }
            var podcast = await _context.Podcast.FindAsync(id);
            if (podcast != null)
            {
                _context.Podcast.Remove(podcast);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PodcastExists(int id)
        {
          return (_context.Podcast?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public IActionResult AddToListenerList(int id)
        {
            Podcast podcast = _context.Podcast.Include(e => e.ListenerLists).FirstOrDefault(p => p.Id == id);
            if (podcast == null)
            {
                return NotFound();
            }

            List<ListenerList> listenerList = _context.ListenerList.Where(a => !a.Podcasts.Any(p => p.Id == id)).ToList();

            AddToListenerListVM vm = new AddToListenerListVM
            {
                Podcast = podcast,
                ListenerLists = listenerList
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult AddToListenerList(int id, int listenerListId)
        {
            Podcast podcast = _context.Podcast.Include(e => e.ListenerLists).FirstOrDefault(p => p.Id == id);
            if (podcast == null)
            {
                return NotFound();
            }

            ListenerList listenerList = _context.ListenerList.Include(l => l.Podcasts).FirstOrDefault(l => l.Id == listenerListId);
            if (listenerList == null)
            {
                return NotFound();
            }

            if (!listenerList.Podcasts.Any(a => a.Id == id))
            {
                listenerList.Podcasts.Add(podcast);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Advanced-Database-and-ORM-Concepts_Assignment 1/Views/Podcasts/AddToListenerList.cshtml
@model Advanced_Database_and_ORM_Concepts_Assignment_1.Models.ViewModels.AddToListenerListVM


<h2>Add to listener list</h2>

<div>
    <p><strong>Podcast:</strong> @Model.Podcast.PodcastTitle</p>
</div>

<form asp-action="AddToListenerList" method="post">
    <div>
        <label for="listenerListId">Select listener list:</label>
        <select id="listenerListId"  name="listenerListId" class="form-control">
            @foreach (ListenerList list in Model.ListenerLists)
            {
                    <option value="@list.Id">@list.ListenerListName</option>
            }
        </select>
    </div>
    <button type="submit">Add to listener list</button>
</form>

Advanced-Database-and-ORM-Concepts_Assignment 1/Views/Podcasts/Create.cshtml
@model Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Podcast</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PodcastTitle" class="control-label"></label>
                <input asp-for="PodcastTitle" class="form-control" />
                <span asp-validation-for="PodcastTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Advanced-Database-and-ORM-Concepts_Assignment 1/Views/Podcasts/Delete.cshtml
@model Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Podcast</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PodcastTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PodcastTitle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Advanced-Database-and-ORM-Concepts_Assignment 1/Views/Podcasts/Details.cshtml
@model Advanced_Database_and_ORM_Concepts_Assignment_1.Models.ViewModels.EpisodeListVM

<h1>@Model.Episodes.Count() Episodes</h1>

@using (Html.BeginForm("Details", "Podcasts"))
{
    @Html.DropDownListFor(a => a.SortFunction, new List<SelectListItem>
    {
        new SelectListItem { Text = "Chronological", Value = "chronological" },
        new SelectListItem { Text = "Reverse-Chronological", Value = "reverse-chronological" }
    }, "Select Sort Option")

        <button type="submit">Sort</button>
}


<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Air Date</th>
            <th>Duration</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Episode episode in Model.Episodes)
        {
            <tr>
                <td>@episode.Title</td>
                <td>@episode.AirDate.ToShortDateString()</td>
                <td>@TimeSpan.FromSeconds(episode.DurationSeconds).ToString("hh\\:mm\\:ss")</td>
            </tr>
            
        }
    </tbody>
</table>

Advanced-Database-and-ORM-Concepts_Assignment 1/Views/Podcasts/Edit.cshtml
@model Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Podcast</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PodcastTitle" class="control-label"></label>
                <input asp-for="PodcastTitle" class="form-control" />
                <span asp-validation-for="PodcastTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Advanced-Database-and-ORM-Concepts_Assignment 1/Views/Podcasts/Index.cshtml
@model IEnumerable<Advanced_Database_and_ORM_Concepts_Assignment_1.Models.Podcast>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Podcasts</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Podcast Title
            </th>
            <th>
                Episodes
            </th>
            <th>
                Listener Lists
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.PodcastTitle
            </td>
            <td>
                @foreach(Episode e in item.Episodes)
                {
                    @e.Title
                }
            </td>
            <td>
                @foreach(ListenerList l in item.ListenerLists)
                {
                    @l.ListenerListName
                }
            </td>

            <td>
                <a asp-action="AddToListenerList" asp-route-id="@item.Id">Add to Listener List</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>